CREATE TABLE IF NOT EXISTS Author (
    AuthorID INTEGER NOT NULL AUTO_INCREMENT,
    FName VARCHAR(100) NOT NULL,
    LName VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (AuthorID)
);

CREATE TABLE IF NOT EXISTS Book (
    ISBN VARCHAR(13) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Genre VARCHAR(100) NOT NULL,
    Title VARCHAR(200) NOT NULL,
    AuthorID INTEGER NOT NULL,
    
    PRIMARY KEY (ISBN),
    FOREIGN KEY (AuthorID) REFERENCES Author(AuthorID)
);

CREATE TABLE IF NOT EXISTS Review (
    ReviewID INTEGER NOT NULL AUTO_INCREMENT,
    ReviewText VARCHAR(512) NOT NULL,
    ISBN VARCHAR(13) NOT NULL,

    PRIMARY KEY (ReviewID),
    FOREIGN KEY (ISBN) REFERENCES Book(ISBN)
);

CREATE TABLE IF NOT EXISTS Publisher (
    PublisherID INTEGER NOT NULL AUTO_INCREMENT,
    PublisherName VARCHAR(100) NOT NULL,

    PRIMARY KEY (PublisherID)
);

CREATE TABLE IF NOT EXISTS PublishedBy (
    Year INTEGER NOT NULL,
    PublisherID INTEGER NOT NULL,
    ISBN VARCHAR(13) NOT NULL,

    PRIMARY KEY (PublisherID, ISBN),
    FOREIGN KEY (PublisherID) REFERENCES Publisher(PublisherID),
    FOREIGN KEY (ISBN) REFERENCES Book(ISBN)
);

CREATE TABLE IF NOT EXISTS CreditCard (
    CardNo VARCHAR(16) NOT NULL,
    CardType VARCHAR(50) NOT NULL,
    ExpDate DATE NOT NULL,

    PRIMARY KEY (CardNo)
);

CREATE TABLE IF NOT EXISTS Customer (
    Username VARCHAR(100) NOT NULL,
    PIN VARCHAR(100) NOT NULL,
    Address VARCHAR(100) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    FName VARCHAR(100) NOT NULL,
    LName VARCHAR(100) NOT NULL,
    CardNo VARCHAR(16) NOT NULL,

    PRIMARY KEY (Username),
    FOREIGN KEY (CardNo) REFERENCES CreditCard(CardNo)
);

CREATE TABLE IF NOT EXISTS PurchaseOf (
    PurchasedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ReceiptID INTEGER NOT NULL AUTO_INCREMENT,
    Username VARCHAR(100) NOT NULL,

    PRIMARY KEY (ReceiptID),
    FOREIGN KEY (Username) REFERENCES Customer(Username)
);

CREATE TABLE IF NOT EXISTS InPurchase (
    Quantity INTEGER NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    ReceiptID INTEGER NOT NULL,

    FOREIGN KEY (ISBN) REFERENCES Book(ISBN),
    FOREIGN KEY (ReceiptID) REFERENCES PurchaseOf(ReceiptID)
);

CREATE TABLE IF NOT EXISTS Admin (
    Username VARCHAR(100) NOT NULL,
    PIN VARCHAR(100) NOT NULL,

    PRIMARY KEY(Username)
);
